/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projectpbo;

/**
 *
 * @author JAGAD
 */
public class menuUtama extends javax.swing.JFrame {
    private String idUser;
    private String namaUser;
    private String roleUser;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(menuUtama.class.getName());

    /**
     * Creates new form menuUtama
     */
    public menuUtama(String idUser, String namaUser, String roleUser) {
        initComponents();
        this.idUser = idUser;
        this.namaUser = namaUser;
        this.roleUser = roleUser;
        User.setText(namaUser);
        Role.setText(roleUser);
        
        if (!roleUser.equals("Admin")) {
            tambahKategori.setVisible(false);
        }
    }

    public menuUtama() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        User = new javax.swing.JLabel();
        Logout = new javax.swing.JButton();
        menuUtama = new javax.swing.JLabel();
        formPengaduan = new javax.swing.JButton();
        daftarPengaduan = new javax.swing.JButton();
        tambahKategori = new javax.swing.JButton();
        Bantuan = new javax.swing.JButton();
        Role = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(400, 300));
        jPanel1.setMinimumSize(new java.awt.Dimension(400, 300));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 300));

        User.setText("Nama_User");

        Logout.setText("Logout");
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });

        menuUtama.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        menuUtama.setText("Menu Utama");

        formPengaduan.setText("Form Pengaduan");
        formPengaduan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formPengaduanActionPerformed(evt);
            }
        });

        daftarPengaduan.setText("Daftar Pengaduan");
        daftarPengaduan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daftarPengaduanActionPerformed(evt);
            }
        });

        tambahKategori.setText("Atur Kategori");
        tambahKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahKategoriActionPerformed(evt);
            }
        });

        Bantuan.setText("Bantuan");

        Role.setText("Role_User");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(122, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(menuUtama)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(daftarPengaduan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(formPengaduan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tambahKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Bantuan, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(62, 62, 62)
                        .addComponent(Logout))
                    .addComponent(User, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Role, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(User)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Role)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Logout)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(menuUtama)
                        .addGap(27, 27, 27)
                        .addComponent(formPengaduan)
                        .addGap(18, 18, 18)
                        .addComponent(daftarPengaduan)
                        .addGap(18, 18, 18)
                        .addComponent(tambahKategori)
                        .addGap(18, 18, 18)
                        .addComponent(Bantuan)))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        // TODO add your handling code here:
        Login login = new Login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LogoutActionPerformed

    private void tambahKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahKategoriActionPerformed
        // TODO add your handling code here:
        Kategori kategori = new Kategori();
        kategori.setVisible(true);
        dispose();
    }//GEN-LAST:event_tambahKategoriActionPerformed

    private void formPengaduanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formPengaduanActionPerformed
        // TODO add your handling code here:
                FormPengaduan fp = new FormPengaduan(idUser, namaUser, roleUser);
                fp.setVisible(true);
                dispose();
    }//GEN-LAST:event_formPengaduanActionPerformed

    private void daftarPengaduanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daftarPengaduanActionPerformed
        // TODO add your handling code here:
        //        DaftarPengaduan dp = new DaftarPengaduan(namaUser, roleUser);
        //        dp.setVisible(true);
        //        dispose();
    }//GEN-LAST:event_daftarPengaduanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new menuUtama().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bantuan;
    private javax.swing.JButton Logout;
    private javax.swing.JLabel Role;
    private javax.swing.JLabel User;
    private javax.swing.JButton daftarPengaduan;
    private javax.swing.JButton formPengaduan;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel menuUtama;
    private javax.swing.JButton tambahKategori;
    // End of variables declaration//GEN-END:variables
}
